build:
	flex tema.l
	gcc lex.yy.c -o temaB -lfl
test1:
	./temaB < intrare-a.html
test2:
	./temaB < intrare-b.html
test3:
	./temaB < intrare-c.html
test4:
	./temaB < intrare-d.html
test5:
	./temaB < intrare-e.html
clean:
	rm temaB lex.yy.c
